# CURRENCY CONFIGURATION
# Docs: https://docs.apigee.com/api-platform/monetization/manage-supported-currencies
# Configuration Properties: https://docs.apigee.com/api-platform/monetization/manage-supported-currencies#configuration-props-api
---
description: "Euro"
displayName: "Euro"
virtualCurrency: "false"
# ISO 4217 currency code (https://en.wikipedia.org/wiki/ISO_4217) 
name: "EUR"
organization:
  # dynamically set
  id: '!INCLUDE{orgName}'
status: "ACTIVE"

# (optional properties)
# creditLimit: 1000
# minimumTopupAmount: 100