# API PRODUCT CONFIGURATION WITH TRANSACTION RECORDING POLICIES
---
name: "mint-kickstart-api-product-v1"
displayName: "Mint Kickstart API Product v1"
approvalType: auto
attributes:
- name: access
  value: public
- name: MINT_TRANSACTION_SUCCESS_CRITERIA
  value: txProviderStatus == 'OK'
- name: transactionRecordingPolicies
  # dynamically set
  value: "!INCLUDE{transactionRecordingPaths.yml}"
description: "Sample Monetization API Product"
apiResources:
- "/"
- "/**"
environments:
- test
proxies:
  # rename if you wish to have a different API proxy name
- "m10n-kickstart-v1"
scopes:
- ''