# API PRODUCT BUNDLE CONFIGURATION
# currently contains one API product, but can contain multiple
---
description: 'Monetization Kickstart Product Bundle'
displayName: 'Mint Kickstart Product Bundle v1'
name: 'mint-kickstart-bundle-v1'
product:
- id: 'mint-kickstart-api-product-v1'
status: 'CREATED'