# API PRODUCT CONFIGURATION WITH TRANSACTION RECORDING POLICIES
# Configuration details:
# - Product quota: 10.000 requests per day
# - Custom attribute for charging API use: "credit-charge"
---
name: "mint-kickstart-product-credits-v1"
displayName: "Mint Kickstart Product Credits v1"
approvalType: auto
attributes:
- name: access
  value: public
- name: credit-charge
  value: "1"
- name: transactionRecordingPolicies
  # dynamically set
  value: "!INCLUDE{transactionRecordingPaths.yml}"
- name: MINT_TRANSACTION_SUCCESS_CRITERIA
  value: "txProviderStatus == 'OK'"
- name: MINT_CUSTOM_ATTRIBUTE_1
  value: "Credit Charge"
description: "credits-based charge for API use"
apiResources:
- "/"
- "/**"
environments:
- test
proxies:
  # rename if you wish to have a different API proxy name
- "mint-kickstart-credits-v1"
quota: "10000"
quotaInterval: "1"
quotaTimeUnit: "day"
scopes:
- ''