# API PRODUCT CONFIGURATION
---
name: "m10n-kickstart-api-product"
displayName: "M10n Kickstart API Product"
approvalType: auto
attributes:
- name: access
  value: public
- name: MINT_TRANSACTION_SUCCESS_CRITERIA
  value: txProviderStatus == 'OK'
description: "Sample Monetization API Product"
apiResources:
- "/"
- "/**"
environments:
- test
# Keep as-is or rename if you name the API proxy differently
proxies:
- "mint-kickstart-v1"
scopes:
- ''
