# CURRENCY CONFIGURATION
# Docs: https://docs.apigee.com/api-platform/monetization/manage-supported-currencies
# Configuration Properties: https://docs.apigee.com/api-platform/monetization/manage-supported-currencies#configuration-props-api
---
description: "Pound Sterling"
displayName: "Pound Sterling"
virtualCurrency: "false"
# ISO 4217 currency code (https://en.wikipedia.org/wiki/ISO_4217) 
name: "GBP"
organization:
  # target organization name
  id: "demo8"
status: "ACTIVE"

# (optional properties)
# creditLimit: 1000
# minimumTopupAmount: 100