- 
  name: "/"
  policies: 
    request: []
    response: "!INCLUDE{transactionRecordingPolicy.yml}"
- 
  name: "/**"
  policies: 
    request: []
    response: "!INCLUDE{transactionRecordingPolicy.yml}"